openapi: 3.0.4
info:
  title: Quotes REST API - OpenAPI 3.0
  description: "Документация к API сервису \"Цитатник\""
  termsOfService: https://swagger.io/terms/
  contact:
    email: ladislao-slobodchikov@yandex.ru
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: Quotes
paths:
  /quotes:
    post:
      tags:
        - Quotes
      summary: Create quote
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQuote'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '400':
          description: Invalid ID supplied
    get:
      tags:
        - Quotes
      summary: Get list of quotes
      parameters:
        - name: author
          in: query
          description: Filter by author
          example: Confucius
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
  /quotes/random:
    get:
      tags:
        - Quotes
      summary: Get random quote
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
  /quotes/{id}:
    delete:
      tags:
        - Quotes
      summary: Delete quote
      parameters:
        - name: id
          in: path
          description: ID of quote
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Success
components:
  schemas:
    CreateQuote:
      type: object
      properties:
        author:
          type: string
          example: Confucius
        quote:
          type: string
          example: Life is good
      required:
        - author
        - quote
    Quote:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        author:
          type: string
          example: Confucius
        quote:
          type: string
          example: Life is good